import type { Homestay } from "@/lib/types";

const districtOneGallery = [
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
];

const thaoDienGallery = [
  "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1600&q=85",
  "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=85",
];

export const homestays: Homestay[] = [
  {
    id: "hs_dalat",
    slug: "district-one-studio-saigon",
    name: "District One Studio",
    location: "District 1, Ho Chi Minh City",
    description:
      "Compact private studios for work breaks, late arrivals, and short city stays near Ben Thanh.",
    rating: 4.92,
    reviewCount: 128,
    priceFrom: 18,
    image: districtOneGallery[0],
    gallery: districtOneGallery,
    tags: ["Hourly", "Overnight"],
    amenities: [
      "Self check-in",
      "Smart TV",
      "Day-use desk",
      "Fast Wi-Fi",
      "Fresh towels",
      "Secure parking",
    ],
    rooms: [
      {
        id: "pine-suite",
        name: "City Nap Studio",
        description: "Quiet room with blackout curtains, shower, desk, and keyless entry.",
        guests: 2,
        beds: "1 queen bed",
        size: "42 m²",
        hourlyPrice: 22,
        overnightPrice: 58,
        dailyPrice: 112,
        minHours: 2,
        maxHours: 12,
        price: 112,
        image: districtOneGallery[1],
        remaining: 2,
      },
      {
        id: "garden-studio",
        name: "Work Break Room",
        description: "Simple studio for calls, rest, or a same-day refresh between plans.",
        guests: 2,
        beds: "1 queen bed",
        size: "31 m²",
        hourlyPrice: 18,
        overnightPrice: 49,
        dailyPrice: 78,
        minHours: 2,
        maxHours: 10,
        price: 78,
        image: districtOneGallery[2],
        remaining: 1,
      },
    ],
  },
  {
    id: "hs_hoian",
    slug: "thao-dien-loft-saigon",
    name: "Thao Dien Loft",
    location: "Thao Dien, Ho Chi Minh City",
    description:
      "Design-led loft rooms for couples, business travelers, and overnight resets in District 2.",
    rating: 4.88,
    reviewCount: 94,
    priceFrom: 16,
    image: thaoDienGallery[0],
    gallery: thaoDienGallery,
    tags: ["Short stay", "Self check-in"],
    amenities: [
      "Self check-in",
      "Bathtub rooms",
      "Fast Wi-Fi",
      "Motorbike parking",
      "Room service partners",
      "Flexible checkout",
    ],
    rooms: [
      {
        id: "river-balcony",
        name: "Loft Bath Room",
        description: "Private loft with soaking tub, soft lighting, and a small work corner.",
        guests: 2,
        beds: "1 king bed",
        size: "36 m²",
        hourlyPrice: 24,
        overnightPrice: 62,
        dailyPrice: 92,
        minHours: 2,
        maxHours: 12,
        price: 92,
        image: thaoDienGallery[1],
        remaining: 3,
      },
      {
        id: "courtyard-family",
        name: "Airport Buffer Suite",
        description: "Larger studio for luggage, shower, and overnight layovers before early flights.",
        guests: 4,
        beds: "1 king + 2 singles",
        size: "48 m²",
        hourlyPrice: 32,
        overnightPrice: 78,
        dailyPrice: 118,
        minHours: 3,
        maxHours: 12,
        price: 118,
        image: thaoDienGallery[2],
        remaining: 1,
      },
    ],
  },
];

export const recentBookings = [
  { ref: "SF-260615-A8K2", guest: "Mina Park", stay: "District One Studio", total: 68, status: "confirmed" },
  { ref: "SF-260614-P3L9", guest: "Daniel Ross", stay: "Thao Dien Loft", total: 96, status: "pending_payment" },
  { ref: "SF-260613-R7M4", guest: "Linh Nguyen", stay: "District One Studio", total: 58, status: "checked_in" },
  { ref: "SF-260612-C2Q1", guest: "Aisha Khan", stay: "Thao Dien Loft", total: 78, status: "paid" },
];
